network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      addresses:
        - 10.10.10.2/24
      nameservers:
        search: [mydomain, otherdomain]
        addresses: [10.10.10.1, 1.1.1.1]
      routes: 
        - to: default
          via: 10.10.10.1
        - to: 192.168.0.0/24
          via: 10.10.10.254
        - to: 172.29.29.0/24
          via: 10.10.10.254
          advertised-mss: 1400
