#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/loadcpufreq" ] ; then
	chmod +x "/etc/init.d/loadcpufreq" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/cpufrequtils" ] ; then
	chmod +x "/etc/init.d/cpufrequtils" >/dev/null || true
fi
# End automatically added section
