#!/bin/sh
set -e
# Automatically added by dh_installsystemduser/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'gpg-agent-browser.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'gpg-agent-extra.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'gpg-agent-ssh.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'gpg-agent.socket' >/dev/null || true
	fi
fi
# End automatically added section
