#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
        if getent passwd usbmux > /dev/null; then
                if command -v deluser > /dev/null; then
                        deluser --system usbmux || echo "Could not remove usbmux user"
                fi
        fi
fi

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
